### ISSUE TITLE
How to use other permissions that are not listed in PermissionUtils

### ISSUE THREAD

**Issue by hasnain-ahmad** [RurioLuca/PermissionManager#1]
I am using your library in my project. I want to check some other permissions that are not listed in the 
PermissionUtils class.
Here are some permissions.

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
<uses-permission android:name="android.permission.RESTART_PACKAGES" />
<uses-permission android:name="android.permission.GET_TASKS" />
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
<uses-permission android:name="android.permission.PACKAGE_USAGE_STATS" />
<uses-permission android:name="android.permission.READ_LOGS" />
```

Here is modified PermissionUtils.java class
http://pastebin.com/PC1MNDCM
Here is the MainActivity.java
http://pastebin.com/yHkSSGed

**Comment by RurioLuca** [comment]
If these permissions are needed to use the application , they must be in the manifest , but you do not need to ask permission runtime !
