### ISSUE TITLE
permissionForeverDenied() not fired

### ISSUE THREAD

**Issue by alessandrotorres** [RurioLuca/PermissionManager#5]
Hi,

I noticed that permissionForeverDenied() in askCompactPermission() is not fired even if user check "Don't ask again" and deny permission.
If I retry, always permissionDenied() is fired.

I'm using a fragment that extends FragmentManagePermission.

Android version 6.0.1

Thanks,
Alessandro

**Comment by RurioLuca** [comment]
Thanks for the report, 
in these days ,I will check the correct operation.

Luca

**Comment by RurioLuca** [comment]
I've fix the problem!
please update your version ;- )

dependencies {
 compile 'com.auron:permission-manage:1.1.7'
}

**Comment by alessandrotorres** [comment]
Hi Luca,

thanks ! Now it's ok :)
