### ISSUE TITLE
until

### ISSUE THREAD

**Issue by CxcCoding** [RurioLuca/PermissionManager#6]
If it can be packed into untils inside will be better, although you are so troublesome but it is a good way

**Comment by RurioLuca** [comment]
Sorry but I did not understand well, can you explain better?
Thank you

**Comment by RurioLuca** [comment]
Sorry I did not understand yet what you wanted to tell me, but i think this is not a bug, but it's a new feature.
If you would like to send me an e-mail to explain what you meant.

Luca
