### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by pejmanghorbani** [RurioLuca/PermissionManager#8]
thanks for ur lib. i am trying to use ur library but i have this error.
![error lib1](https://user-images.githubusercontent.com/46624874/61033818-10383480-a379-11e9-8fd4-c18bedcf6e91.jpg)

![error lib](https://user-images.githubusercontent.com/46624874/61033613-b2a3e800-a378-11e9-997f-bfc725dc9bc7.png)

**Comment by RurioLuca** [comment]
hello,
 you should use "implementation" instead of "compile" to have no transitive dependencies.
Alternatively, have you installed buildTools 28?

**Comment by pejmanghorbani** [comment]
i havnt install build tools 28 .if i do that does my project get any error?

**Comment by RurioLuca** [comment]
you can install the build tools and let your project compile with the old version, you will have no problems.
It would be better if you migrated the dependencies from "compile" to "implementation".

**Comment by pejmanghorbani** [comment]
thanks for ur help ang good library...
